### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by kobrin666** [cerebnismus/script-practice#1]
Hi bro.
what site is this key from?
solver.set_key("ed22770ac73212ee52523d36e59be6a4")
if I insert the key from the site https://anti-captcha.com/ then I get the following error

`    driver.execute_script("___grecaptcha_cfg.clients[0].B.B.callback('onSuccessCallback(e){this.ngZone.run(()=>this.recaptchaSuccess.
emit(e))}');")
  File "C:\Users\Slon\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 492, in
execute_script
    return self.execute(command, {
  File "C:\Users\Slon\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in
execute
    self.error_handler.check_response(response)
  File "C:\Users\Slon\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243,
in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'B')
  (Session info: chrome=109.0.5414.75)`

**Comment by cerebnismus** [comment]
I just exposed my old private api key, you should register anti-captcha.com and get your  own api key.

**Comment by kobrin666** [comment]
I installed my key from this site instead of yours, after that such problems began. Your key worked well, but mine doesn't. maybe some settings on the site for api are needed? Thank you

**Comment by kobrin666** [comment]
> I just exposed my old private api key, you should register anti-captcha.com and get your own api key.

I installed my key from this site instead of yours, after that such problems began. Your key worked well, but mine doesn't. maybe some settings on the site for api are needed? Thank you

**Comment by kobrin666** [comment]
can you test my api key?

**Comment by cerebnismus** [comment]
Did you pay for your api balance ?

**Comment by cerebnismus** [comment]
you just spent my 4$ bro :) never mind

**Comment by kobrin666** [comment]
> Did you pay for your api balance ?

sure. mine key bd47ba1a03957630fb2aea7efcc35c43 but i have only 0.10 dollars

**Comment by kobrin666** [comment]
> ты только что потратил мои 4$ братан :) неважно

where to transfer, I did not want)))

**Comment by kobrin666** [comment]
I am not a programmer, but I am also writing code for Turkey now. if you want, we can talk on whatsapp or telegram. I will show what I have and what I want to get in the end
